package paweltypiak.weatherial.introActivityInitializing.introActivityFragmentInitializing.introActivityConfigurationFragmentInitializing;

public interface OnSettingsFragmentViewCreatedListener {
    void fadeInConfigurationFragmentLayout();
}
