package paweltypiak.matweather.introActivityInitializing.introActivityFragmentInitializing.introActivityConfigurationFragmentInitializing;

public interface OnSettingsFragmentViewCreatedListener {
    void fadeInConfigurationFragmentLayout();
}
