package paweltypiak.matweather.introActivityInitializing.introActivityFragmentInitializing.introActivityLoadingFragmentInitializing;

public interface OnRequestLocalizationPermissionsListener {
    void requestLocalizationPermissions();
}
