package paweltypiak.weatherial.introActivityInitializing.introActivityFragmentInitializing.introActivityLoadingFragmentInitializing;

public interface OnRequestLocalizationPermissionsListener {
    void requestLocalizationPermissions();
}
